# src/first_agent/config/tasks.yaml
research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
  output_file: report.md

product_design_task:
  description: >
    Review the context you got and craft 5 products with their finer details. Make sure all the technical details related with each product is 
    included in report.
  expected_output: >
    A fully fledge reports with the mains topics(products), each with a full section of information.
    Formatted as markdown without '```'
  agent: product_designer
  output_file: product.md